<?php

function sd_perm() {
  return array('access gettwitterdata');
}

function sd_menu() {

  $items['timeline/pull/twitter'] = array( //api para stats
    'title' => '',
    'page callback' => 'sd_gettw',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	return $items;
} 

function sd_gettw(){

	//Recuerde: hay un limite de 120 llamadas por hora por ip
	$tw_last_id = variable_get('tw_last_id', 1);

	//media credit rules
	$msite = array(
			'lanacion' => 'La Nación',
			'larazon' => 'La Razón',
			'cronica' => 'Diario Crónica',
			'diariopopular' => 'Diario Popular',
			'clarin' => 'Clarín',
			'diariocuyo' => 'Diario Cuyo',
			'diariorionegro' => 'Diario Río Negro',
			'lavanguardia' => 'La Vanguardia',
			'elpais' => 'El País',
			'theguardian' => 'The Guardian',
			'bbc' => 'BBC',
			'1982' => 'Efemerídes',
			'comunicado' => 'Comunicado Oficial',
		);

	//media caption rules
	$country = array(
			'arg' => 'Argentina',
			'esp' => 'España',
			'uk' => 'Gran Bretaña',
			'pe' => 'Perú',
		);

	//exclude 
	$exclude = array('blog', 'sitio');

	//prod
	$feedjson = "https://api.twitter.com/1/statuses/user_timeline.json?include_entities=true&screen_name=malvinas30&since_id=".$tw_last_id;
	//dev
	//$feedjson = "http://indexante.com/gettw.php";

	//get data
	$localjson = file_get_contents($feedjson);
	$twjson = json_decode($localjson, true);

	//vars 
	$last_id = '';

	//parsear los datos
	foreach ($twjson as $k => $d) {

		//vars
		$tags = array();
		$publish = 1;
		$media = '';
		$assets = array();

		if($last_id==''){
			$last_id = $d['id_str'];
			variable_set('tw_last_id', $d['id_str']);
		}

		$past_time = strtotime($d['created_at']);
		$past_time_str = (date('Y-',$past_time)-30).date('-n-j',$past_time);
		$past_time = strtotime($past_time_str);

		if(isset($d['entities']['media'][0]['media_url'])){
			$media = $d['entities']['media'][0]['media_url'];
		}

		if(isset($d['entities']['urls'][0]['expanded_url'])){
			$media = $d['entities']['urls'][0]['expanded_url'];
		}

		//obtiene hashtags
		if(count($d['entities']['hashtags']) > 0){
			foreach($d['entities']['hashtags'] as $k => $h ){
				$tags[$k] = $h['text'];

				if( ($tags[$k]=='blog') OR ($tags[$k]=='sitio') OR ($tags[$k]=='vivo') ){
					$publish = 0;
					break;
				}

			}
		}

		//buscar media credit y media caption
		if( count($tags) > 0) {
			$mediacc[0] = $msite;
			$mediacc[1] = $country;

			foreach($mediacc as $i => $arr ){

				foreach($tags as $k => $t){

				$t = strtolower($t);

					if( array_key_exists($t, $arr) ){
						$assets[$i] = $arr[$t];
						//echo 'asset '.$i.' : '.$t.' :'.$arr[$t].'<br/>';
						break;
					}

				}
			}

		}

		if($publish){

			$title = preg_replace('/\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|$!:,.;]*[A-Z0-9+&@#\/%=~_|$]/i', '', $d['text']);
			$body = '';

			$ex = explode("&gt;", $title, 2);
			if(is_array($ex)){
				$title = $ex[0];
				$body = $ex[1];
			}

			$url = parse_url($media);
			
			if($url['host'] == 'ow.ly'){
				$body .= ' '.$media;
				$media = '';
			}

			$mytags = implode(', ', $tags);
			
			/*
			echo $d['id_str'].'<br/>';
			echo $title.'<br/>';
			echo 'body : '.$body.'<br/>';
			echo 'media : '.$media.'<br/>';
			echo 'media credit : '.$assets[0].'<br/>';
			echo 'media caption : '.$assets[1].'<br/>';
			echo 'tags : '.$mytags.'<br/>';
			echo '<hr/>';
			*/
			
			
			$node = new stdClass();

			$node->type = 'timeline';
			$node->uid = $user->uid;
			$node->title = $title;
			$node->body = $body;

			$node->field_startdatetime[0]['value']= $past_time;
			$node->field_media[0]['value'] = $media;

			// this is the code for saving the free tag taxonomy terms
			if($mytags){
				$node->taxonomy = array(
 					'tags' => array(
 						'1' => strtolower($mytags)
 					)
 				);	
			}
 			
			//$node = node_submit($node);
			
			node_save($node);	
		}
		else{
			echo '<hr/>no publica : '.$d['text'].'<hr/>';
		}
		
	}

	echo $last_id;

	die('');

	return true;
}
