<?php

function sd_perm() {
  return array('access gettwitterdata');
}

function sd_menu() {

  $items['timeline/pull/twitter'] = array( //api para stats
    'title' => '',
    'page callback' => 'sd_gettw',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	return $items;
} 

function sd_gettw(){

	//Recuerde: hay un limite de 120 llamadas por hora por ip
	$tw_last_id = variable_get('tw_last_id');
	$feedjson = "https://api.twitter.com/1/statuses/user_timeline.json?include_entities=true&screen_name=malvinas30&since_id=";

	$localjson = file_get_contents($feedjson);
	$twjson = json_decode($localjson, true);

	$last_id = '';

	//parsear los datos
	foreach ($twjson as $k => $d) {

		echo $d['id_str'].', ';

		if($last_id==''){
			$last_id = $d['id_str'];
			variable_set('tw_last_id', $d['id_str']);
		}

		$past_time = strtotime($d['created_at']);
		$past_time_str = (date('Y-',$past_time)-30).date('-n-j',$past_time);
		$past_time = strtotime($past_time_str);

		$media = '';

		if(isset($d['entities']['media'][0]['media_url'])){
			$media = $d['entities']['media'][0]['media_url'];
		}

		if(isset($d['entities']['urls'][0]['expanded_url'])){
			$media = $d['entities']['urls'][0]['expanded_url'];
		}

		//echo ':'.$media.'<hr/>';

		$node = new stdClass();

		$node->type = 'timeline';
		$node->uid = $user->uid;
		$node->title = preg_replace('/\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|$!:,.;]*[A-Z0-9+&@#\/%=~_|$]/i', '', $d['text']);
		$node->body = '';

		$node->field_startdatetime[0]['value']= $past_time;
		$node->field_media[0]['value'] = $media;

		node_save($node);
	}

	echo $last_id;

	die('');

	return true;
}